packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: 9.21.0
  prettier: ^3.5.2
  typescript: ^5.7.2
  zod: ^3.23.8
  postcss: ^8.5.3
  tsup: ^8.4.0

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
