name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create_pr:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # Optionally enable caching for pnpm:
          # cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Pre-publish requirements
        run: pnpm build && pnpm lint

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          # Use pnpm to run your version script
          version: pnpm run changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: create_pr
    if: needs.create_pr.outputs.hasChangesets == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # Optionally enable caching for pnpm:
          # cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Pre-publish requirements
        run: pnpm build && pnpm lint

      - name: release
        id: changesets
        uses: changesets/action@v1
        with:
          # Use pnpm to run your release script
          publish: pnpm run changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
